name: mvce

on:
  push:

env:
  TF_IN_AUTOMATION: true

jobs:
  prod-plan:
    runs-on: ubuntu-latest
    outputs:
      plan-has-changes: ${{ steps.plan.outputs.plan-has-changes }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Set up Terraform"
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.1

      - name: "terraform init"
        run: terraform init --input=false

      - name: "Check for changes in Terraform plan"
        id: plan
        shell: python
        run: |
          import subprocess
          import sys

          command = ["terraform", "plan", "--input=false", "--detailed-exitcode"]
          exit_code = subprocess.run(command, check=False).returncode

          print(f"Exit code: {exit_code}")

          if exit_code == 0:
              plan_has_changes = False
          elif exit_code == 2:
              plan_has_changes = True
          else:
              sys.exit(exit_code)

          print(f"::set-output name=plan-has-changes::{plan_has_changes}")

  prod-approve:
    runs-on: ubuntu-latest
    needs: [ prod-plan ]
    if: ${{ needs.prod-plan.outputs.plan-has-changes == 'true' }}
    steps:
      - run: echo "Plan has changes"
